import { useMemo, useState } from 'react';
import { Landmark, Download, CheckCircle2, AlertTriangle, Loader2 } from 'lucide-react';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import { getDefaultProbability } from './RiskStressTestCard';
import { structureGreenBond, GreenBondDeal } from '@/utils/structureGreenBond';
import type { BondMetrics } from '@/components/hud/ScenarioSandbox';

interface DealTicketCardProps {
  financialData: any | null;
  locationName: string | null;
  isLoading?: boolean;
  monteCarloData?: any | null;
  capexBudget?: number | null;
  bondMetrics?: BondMetrics | null;
}

const formatCurrency = (value: number) => {
  if (Math.abs(value) >= 1_000_000) return `$${(value / 1_000_000).toFixed(1)}M`;
  if (Math.abs(value) >= 1_000) return `$${(value / 1_000).toFixed(0)}K`;
  return `$${value.toFixed(0)}`;
};

function DataRow({ label, value, valueColor }: { label: string; value: React.ReactNode; valueColor?: string }) {
  return (
    <div className="flex items-center justify-between py-2.5 cb-divider">
      <span className="cb-label">{label}</span>
      <span className="cb-value" style={valueColor ? { color: valueColor } : {}}>
        {value}
      </span>
    </div>
  );
}

export const DealTicketCard = ({ financialData, locationName, isLoading, monteCarloData, capexBudget, bondMetrics }: DealTicketCardProps) => {
  const deal: GreenBondDeal | null = useMemo(() => {
    if (!financialData) return null;
    return structureGreenBond(financialData);
  }, [financialData]);

  const principalDisplay = capexBudget != null ? formatCurrency(capexBudget) : (deal ? formatCurrency(deal.principal) : '—');
  const couponDisplay = bondMetrics?.green_rate != null
    ? `${Number(bondMetrics.green_rate).toFixed(2)}%`
    : (deal ? `${deal.coupon.toFixed(2)}%` : '5.00%');
  const greeniumValue = bondMetrics?.total_greenium_savings != null
    ? Number(bondMetrics.total_greenium_savings)
    : (deal?.greenium_savings ?? 0);
  const greeniumDisplay = formatCurrency(greeniumValue);
  const greeniumPositive = greeniumValue > 0;

  const [isExporting, setIsExporting] = useState(false);

  const isBankable = useMemo(() => {
    if (monteCarloData) {
      const defaultProb = getDefaultProbability(monteCarloData);
      return defaultProb < 2;
    }
    return deal
      ? deal.rating.startsWith('AAA') || deal.rating.startsWith('BBB')
      : false;
  }, [deal, monteCarloData]);

  const handleExportPDF = async () => {
    try {
      setIsExporting(true);
      const el = document.getElementById('finance-prospectus-printable');
      if (!el) return;
      const canvas = await html2canvas(el, {
        useCORS: true,
        scale: 2,
        backgroundColor: '#0a0a0a',
        logging: false,
      });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const pageW = pdf.internal.pageSize.getWidth();
      const pageH = pdf.internal.pageSize.getHeight();
      const pxToMm = 25.4 / 96;
      let wMm = canvas.width * pxToMm;
      let hMm = canvas.height * pxToMm;
      const ratio = Math.min(pageW / wMm, pageH / hMm, 1) * 0.95;
      wMm *= ratio;
      hMm *= ratio;
      pdf.addImage(imgData, 'PNG', (pageW - wMm) / 2, (pageH - hMm) / 2, wMm, hMm);
      pdf.save('Climate_Resilience_Prospectus.pdf');
    } finally {
      setIsExporting(false);
    }
  };

  const handleExport = () => {
    if (!deal) return;
    const lines = [
      '═══════════════════════════════════════',
      '       GREEN BOND TERM SHEET',
      '═══════════════════════════════════════',
      '',
      `Location:       ${locationName ?? 'N/A'}`,
      `Principal:      ${formatCurrency(deal.principal)}`,
      `Coupon Rate:    ${deal.coupon.toFixed(2)}%`,
      `Tenor:          ${deal.tenor} years`,
      `Credit Rating:  ${deal.rating}`,
      `Greenium:       ${formatCurrency(deal.greenium_savings)} (est. savings)`,
      '',
      `Bankability:    ${isBankable ? 'Bankable Deal' : 'Blended Finance Required'}`,
      '',
      '───────────────────────────────────────',
      `Generated by Resilient Climate Platform`,
      `Date: ${new Date().toISOString().split('T')[0]}`,
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `green-bond-term-sheet-${(locationName ?? 'deal').replace(/\s+/g, '-').toLowerCase()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="px-4 py-4 space-y-3">
        <div className="flex items-center gap-2">
          <Loader2 style={{ width: 10, height: 10, color: '#f59e0b' }} className="animate-spin" />
          <span className="cb-section-heading">CALCULATING...</span>
        </div>
        <div style={{ height: 120, backgroundColor: 'var(--cb-surface)' }} />
      </div>
    );
  }

  if (!deal) {
    return (
      <div className="px-4 py-6 text-center">
        <Landmark style={{ width: 16, height: 16, color: 'var(--cb-secondary)', margin: '0 auto 8px' }} />
        <p style={{ fontSize: 11, color: 'var(--cb-secondary)', lineHeight: 1.6 }}>
          Click a Global Atlas pin or run a simulation to generate a deal ticket.
        </p>
      </div>
    );
  }

  return (
    <div>
      <div className="px-4 pt-3 pb-2 flex items-center justify-between" style={{ borderBottom: '1px solid var(--cb-border)' }}>
        <div className="flex items-center gap-2">
          <Landmark style={{ width: 10, height: 10, color: 'var(--cb-secondary)' }} />
          <span className="cb-section-heading">GREEN BOND TERM SHEET</span>
        </div>
        <div
          className="flex items-center gap-1"
          style={{
            border: '1px solid var(--cb-border)',
            padding: '1px 6px',
            fontFamily: 'monospace',
            fontSize: 10,
            letterSpacing: '0.05em',
            color: isBankable ? '#10b981' : '#f59e0b',
          }}
        >
          {isBankable ? (
            <>
              <CheckCircle2 style={{ width: 8, height: 8 }} />
              BANKABLE
            </>
          ) : (
            <>
              <AlertTriangle style={{ width: 8, height: 8 }} />
              BLENDED FINANCE
            </>
          )}
        </div>
      </div>

      <div className="px-4">
        <DataRow label="PRINCIPAL (CAPEX)" value={principalDisplay} valueColor="#f59e0b" />
        <DataRow label="COUPON RATE" value={couponDisplay} />
        <DataRow label="TENOR" value={`${deal.tenor} yr`} />
        <DataRow label="CREDIT RATING" value={deal.rating.split(' ')[0]} />
        <DataRow
          label="GREENIUM SAVINGS"
          value={greeniumDisplay}
          valueColor={greeniumPositive ? '#22c55e' : undefined}
        />
      </div>

      <div className="px-4 py-3" style={{ borderTop: '1px solid var(--cb-border)' }}>
        <button
          type="button"
          onClick={handleExportPDF}
          disabled={isExporting}
          className="flex items-center gap-2 w-full justify-center"
          style={{
            border: '1px solid var(--cb-border)',
            padding: '6px 12px',
            fontFamily: 'monospace',
            fontSize: 10,
            letterSpacing: '0.08em',
            color: isExporting ? 'var(--cb-secondary)' : 'var(--cb-secondary)',
            backgroundColor: 'transparent',
            cursor: isExporting ? 'wait' : 'pointer',
            transition: 'color 0.15s, border-color 0.15s',
            opacity: isExporting ? 0.7 : 1,
          }}
          onMouseEnter={e => {
            if (!isExporting) {
              (e.currentTarget as HTMLButtonElement).style.color = 'var(--cb-text)';
              (e.currentTarget as HTMLButtonElement).style.borderColor = 'var(--cb-text)';
            }
          }}
          onMouseLeave={e => {
            (e.currentTarget as HTMLButtonElement).style.color = 'var(--cb-secondary)';
            (e.currentTarget as HTMLButtonElement).style.borderColor = 'var(--cb-border)';
          }}
        >
          {isExporting ? (
            <>
              <Loader2 style={{ width: 10, height: 10 }} className="animate-spin" />
              GENERATING PDF...
            </>
          ) : (
            <>
              <Download style={{ width: 10, height: 10 }} />
              EXPORT PROSPECTUS
            </>
          )}
        </button>
      </div>
    </div>
  );
};
